### ISSUE TITLE
Create [PROJECT EMAIL ADDRESS]

### ISSUE THREAD

**Issue by ff6347** [ExtendScript/organisation-rules#1]
We need a address where we can receive things. Like for example stated in the CODE_OF_CONDUCT.md under "enforcement"

**Comment by ozalto** [comment]
Hello,

Why not sth like issues-extendscript@gmail.com ?

**Comment by ff6347** [comment]
I was thinking of getting the extendscript.org domain

**Comment by ozalto** [comment]
That would certainly makes sense.

**Comment by ff6347** [comment]
Got the domain http://extendscript.org and also an address hello@extendscript.org

**Comment by wridgers** [comment]
@fabiantheblind Do you think you would be able to set up a mailing list?

**Comment by ff6347** [comment]
@wridgers setting up a mailing list should be possible. I actually would prefer using gitter or slack instead of e-mail but we should set this up for a vote. I'll create a issue here. (Thats the one everybody is watching) Then we can see what are the preferences.
