### ISSUE TITLE
member or owner?

### ISSUE THREAD

**Issue by ff6347** [ExtendScript/organisation-rules#3]
Dear members. For starters I invited you all as owners of this org. I know from at least 2 people that they can not contribute content right away. I would suggest reducing the number of owners to the active ones and keep everybody else as member. Please give me some feedback if you want to stay owner or if we should set you to member. Of course everyone that starts contributing will be granted owner rights again. If you are a member you wont be added to every newly created repository.

**Comment by wridgers** [comment]
I am happy to stay an owner. I plan on being active and contributing.

**Comment by grefel** [comment]
I would like to stay owner.

**Comment by michamedia** [comment]
I also would like to stay a owner.

**Comment by ff6347** [comment]
I changed everybody else to an member for now. If somebody wants to become owner again please let us know.

**Comment by ozalto** [comment]
I am ok with being a member. I really like the initiative but not sure about how active I will be :P

**Comment by ff6347** [comment]
@ozalto no problemo we will see. What I always did with the wiki was adding a page when I answered a question on stackoverflow or found something out that I wanted to write down for future reference.
