### ISSUE TITLE
codes of conduct 

### ISSUE THREAD

**Issue by ff6347** [ExtendScript/organisation-rules#4]
Maybe in there is something that fits more our needs https://github.com/1000miles/coc-collections/blob/master/README.md

A collection of codes of conduct

**Comment by dominikwilkowski** [comment]
COCs are hard to get right. Let me throw in our short version that held up to the legal department standards of the bank I work for:
https://github.com/WestpacCXTeam/GUI-source/blob/master/.github/CONTRIBUTING.md

(We also have a happy tone of voice so that might need to be changed)

**Comment by ff6347** [comment]
Thanks @dominikwilkowski you are welcome to improve and edit the COC. As already said. We are at the beginning of forming up

**Comment by GitBruno** [comment]
OK I have [started the process](https://github.com/ExtendScript/organisation-rules/pull/7)

**Comment by GitBruno** [comment]
Done #7
