### ISSUE TITLE
Photoshop Design Space

### ISSUE THREAD

**Issue by antonio-gomez** [ExtendScript/organisation-rules#6]
@ExtendScript/all-members 

Hello guys,

I was wondering, now on Photoshop 2017, the design space preview was killed and the last commit for the project was around 2 years ago: https://github.com/adobe-photoshop/spaces-design

I was wondering if any of you has played with Adobe Generator and if anybody sees that it's fate would be the same that design space.

Photoshop panels are powerful, but Generator has some pretty cool features missing on CEP.

-Antonio

**Comment by undavide** [comment]
Hi @antonio-gomez, I don't think so. I mean, I have no official nor confidential information about Generator, but it is used internally for assets... generation (as the name implies), and I doubt Adobe will kill such a feature without a proper replacement.

That said, thanks god I've never messed with Design Space, I've already a nice collection of wasted time in my archives :-)

–Davide

**Comment by antonio-gomez** [comment]
Thanks @undavide

Actually I was wondering what is beyond the regular "Image Assets" feature, like obtaining the document **pixmap** or listening to events with __generator.onPhotoshopEvent_ like toolChanged, currentDocumentChanged, generatorMenuChanged and imageChanged some of them are very useful to trigger custom functionality but it's pretty easy to make Generator unstable and make it crash if they are not used properly.

Most of all Generator custom plugins are dead or not longer maintained, so due to that lack of popularity I'm worried that would have the same fate as Photoshop Design Space. :(

**Comment by undavide** [comment]
When it comes to Adobe, one really never knows... By the way, is there any official news about Design Space being discontinued (besides being _practically discontinued_)?

**Comment by antonio-gomez** [comment]
The only references are these:

https://helpx.adobe.com/rs/photoshop/using/designspace.html
https://helpx.adobe.com/photoshop/using/whats-new.html#Whatschanged

**Comment by JavierAroche** [comment]
It feels like they shifted their focus onto [Adobe XD](http://www.adobe.com/products/experience-design.html). I didn't find an official post saying they killed the project though.

Something I just noticed is @joelrbrandt is no longer with Adobe :(
http://joelbrandt.org/cv/

**Comment by GitBruno** [comment]
Closing this now. Feel free to reopen under [AMA](https://github.com/ExtendScript/AMA/issues)
